services:
  - type: web
    name: taskpulse-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: QUEUE_CONNECTION
        value: redis
      - key: CACHE_STORE
        value: redis
      - key: REDIS_CLIENT
        value: predis
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: taskpulse-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: taskpulse-postgres
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: taskpulse-postgres
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: taskpulse-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: taskpulse-postgres
          property: password
      - key: REDIS_HOST
        fromService:
          type: redis
          name: taskpulse-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: taskpulse-redis
          property: port

  - type: worker
    name: taskpulse-horizon
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    dockerCommand: php artisan horizon
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: QUEUE_CONNECTION
        value: redis
      - key: CACHE_STORE
        value: redis
      - key: REDIS_CLIENT
        value: predis
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: taskpulse-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: taskpulse-postgres
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: taskpulse-postgres
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: taskpulse-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: taskpulse-postgres
          property: password
      - key: REDIS_HOST
        fromService:
          type: keyvalue
          name: taskpulse-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: keyvalue
          name: taskpulse-redis
          property: port

  - type: keyvalue
    name: taskpulse-redis
    plan: starter
    ipAllowList:
      - source: 0.0.0.0/0
        description: public access for app and worker


databases:
  - name: taskpulse-postgres
    plan: basic-256mb
